# Change these first
owner: foneazmi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: foneazmi

sites:
  - name: Web Khan
    url: https://khan.my.id
    icon: https://khan.my.id/icon.svg
  - name: Api Khan
    url: https://api.khan.my.id
    icon: https://khan.my.id/icon.svg
  - name: Pocket Base
    url: https://pb.khan.my.id/api/health
    icon: https://pocketbase.io/images/favicon/favicon-32x32.png
  - name: File Khan
    url: https://file.khan.my.id

assignees:
  - foneazmi

status-website:
  theme: night
  cname: foneazmi.github.io/status
  baseUrl: /status
  logoUrl: https://khan.my.id/icon.svg
  name: Status
  navbar:
    - title: About Me
      href: https://khan.my.id

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
