# Change these first
owner: foneazmi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Khan
    url: https://khan.my.id
  - name: Api Khan
    url: https://api.khan.my.id
  - name: Files
    url: https://file.khan.my.id
  - name: Stock
    url: https://stock.khan.my.id
  - name: Bookkeeping
    url: https://ez.khan.my.id
  - name: Pocketbase
    url: $PB_URL
assignees:
  - foneazmi
status-website:
  cname: status.khan.my.id
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
