# Change these first
owner: foneazmi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personnal website
    url: https://khan.my.id
  - name: Files
    url: https://file.khan.my.id
  - name: DB
    url: https://pb.khan.my.id
assignees:
  - foneazmi
status-website:
  cname: foneazmi.github.io
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
